package com.example.localization

enum class SupportedLanguage(val code: String, val nativeName: String) {
    EN("en", "English"),
    HI("hi", "हिन्दी (Hindi)"),
    TE("te", "తెలుగు (Telugu)"),
    TA("ta", "தமிழ் (Tamil)"),
    KN("kn", "ಕನ್ನಡ (Kannada)"),
    ML("ml", "മലയാളം (Malayalam)"),
    MR("mr", "मराठी (Marathi)"),
    BN("bn", "বাংলা (Bengali)"),
    GU("gu", "ગુજરાતી (Gujarati)"),
    PA("pa", "ਪੰਜਾਬੀ (Punjabi)"),
    AS("as", "অসমীয়া (Assamese)"),
    OR("or", "ଓଡ଼ିଆ (Odia)")
}

object LanguageManager {

    private val translations = mapOf(
        SupportedLanguage.EN to mapOf(
            "app_name" to "Smart Ration PDS",
            "verify_card" to "Verify Smart Ration Card",
            "scan_qr" to "SCAN QR CODE",
            "scan_barcode" to "SCAN BARCODE",
            "tap_nfc" to "TAP NFC CARD",
            "distribute" to "DISTRIBUTE RATION",
            "confirm_distribution" to "CONFIRM DISTRIBUTION",
            "print_receipt" to "PRINT RECEIPT",
            "face_auth" to "FACE RECOGNITION",
            "verified" to "VERIFIED",
            "entitlement" to "Entitlement",
            "remaining" to "Remaining",
            "rice" to "Rice",
            "wheat" to "Wheat",
            "sugar" to "Sugar",
            "monthly" to "Monthly Distribution",
            "three_month" to "3-Month Distribution",
            "offline_mode" to "Offline Mode Active",
            "complaint" to "File Grievance / Complaint",
            "audit_log" to "Audit Trail & Fraud Alerts"
        ),
        SupportedLanguage.HI to mapOf(
            "app_name" to "स्मार्ट राशन वितरण प्रणाली",
            "verify_card" to "स्मार्ट राशन कार्ड सत्यापित करें",
            "scan_qr" to "क्यूआर कोड स्कैन करें",
            "scan_barcode" to "बारकोड स्कैन करें",
            "tap_nfc" to "एनएफसी कार्ड टैप करें",
            "distribute" to "राशन वितरण करें",
            "confirm_distribution" to "वितरण की पुष्टि करें",
            "print_receipt" to "रसीद प्रिंट करें",
            "face_auth" to "चेहरा प्रमाणीकरण (Face Auth)",
            "verified" to "सत्यापित",
            "entitlement" to "कुल पात्रता",
            "remaining" to "शेष मात्रा",
            "rice" to "चावल",
            "wheat" to "गेहूँ",
            "sugar" to "चीनी",
            "monthly" to "मासिक वितरण",
            "three_month" to "3-माह का अग्रिम वितरण",
            "offline_mode" to "ऑफ़लाइन मोड सक्रिय",
            "complaint" to "शिकायत दर्ज करें",
            "audit_log" to "ऑडिट लॉग एवं सुरक्षा अलर्ट"
        ),
        SupportedLanguage.TE to mapOf(
            "app_name" to "స్మార్ట్ రేషన్ పంపిణీ వ్యవస్థ",
            "verify_card" to "స్మార్ట్ రేషన్ కార్డు ధృవీకరించండి",
            "scan_qr" to "క్యూఆర్ కోడ్ స్కాన్ చేయండి",
            "scan_barcode" to "బార్‌కోడ్ స్కాన్",
            "tap_nfc" to "ఎన్‌ఎఫ్‌సి కార్డు ట్యాప్ చేయండి",
            "distribute" to "రేషన్ పంపిణీ చేయండి",
            "confirm_distribution" to "పంపిణీని నిర్ధారించండి",
            "print_receipt" to "రసీదు ముద్రించండి",
            "face_auth" to "ముఖ గుర్తింపు (Face Auth)",
            "verified" to "ధృవీకరించబడింది",
            "entitlement" to "అర్హత",
            "remaining" to "మిగిలిన కోటా",
            "rice" to "బియ్యం",
            "wheat" to "గోధుమలు",
            "sugar" to "చక్కెర",
            "monthly" to "నెలవారీ పంపిణీ",
            "three_month" to "3 నెలల పంపిణీ",
            "offline_mode" to "ఆఫ్‌లైన్ మోడ్ యాక్టివ్",
            "complaint" to "ఫిర్యాదు దాఖలు చేయండి",
            "audit_log" to "ఆడిట్ లాగ్"
        ),
        SupportedLanguage.TA to mapOf(
            "app_name" to "ஸ்மார்ட் ரேஷன் விநியோக முறை",
            "verify_card" to "ரேஷன் கார்டை சரிபார்க்கவும்",
            "scan_qr" to "QR குறியீட்டை ஸ்கேன் செய்",
            "scan_barcode" to "பார்கோடு ஸ்கேன்",
            "tap_nfc" to "NFC கார்டைத் தட்டவும்",
            "distribute" to "ரேஷன் விநியோகிக்கவும்",
            "confirm_distribution" to "விநியோகத்தை உறுதிப்படுத்து",
            "print_receipt" to "ரசீதை அச்சிடுக",
            "face_auth" to "முக அங்கீகாரம்",
            "verified" to "சரிபார்க்கப்பட்டது",
            "entitlement" to "உரிமை அளவு",
            "remaining" to "மீதமுள்ள அளவு",
            "rice" to "அரிசி",
            "wheat" to "கோதுமை",
            "sugar" to "சர்க்கரை",
            "monthly" to "மாதாந்திர விநியோகம்",
            "three_month" to "3 மாத விநியோகம்",
            "offline_mode" to "ஆஃப்லைன் பயன்முறை",
            "complaint" to "புகார் பதிவு",
            "audit_log" to "தணிக்கை பதிவு"
        ),
        SupportedLanguage.KN to mapOf(
            "app_name" to "ಸ್ಮಾರ್ಟ್ ಪಡಿತರ ವಿತರಣಾ ವ್ಯವಸ್ಥೆ",
            "verify_card" to "ಪಡಿತರ ಚೀಟಿ ಪರಿಶೀಲಿಸಿ",
            "scan_qr" to "ಕ್ಯೂಆರ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
            "scan_barcode" to "ಬಾರ್‌ಕೋಡ್ ಸ್ಕ್ಯಾನ್",
            "tap_nfc" to "NFC ಟ್ಯಾಪ್ ಮಾಡಿ",
            "distribute" to "ಪಡಿತರ ವಿತರಿಸಿ",
            "confirm_distribution" to "ವಿತರಣೆಯನ್ನು ದೃಢೀಕರಿಸಿ",
            "print_receipt" to "ರಶೀದಿ ಮುದ್ರಿಸಿ",
            "face_auth" to "ಮುಖ ದೃಢೀಕರಣ",
            "verified" to "ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
            "entitlement" to "ಅರ್ಹತೆ",
            "remaining" to "ಉಳಿದದ್ದು",
            "rice" to "ಅಕ್ಕಿ",
            "wheat" to "ಗೋಧಿ",
            "sugar" to "ಸಕ್ಕರೆ",
            "monthly" to "ಮಾಸಿಕ ವಿತರಣೆ",
            "three_month" to "3 ತಿಂಗಳ ವಿತರಣೆ",
            "offline_mode" to "ಆಫ್‌ಲೈನ್ ಮೋಡ್",
            "complaint" to "ದೂರು ದಾಖಲಿಸಿ",
            "audit_log" to "ಆಡಿಟ್ ಲಾಗ್"
        ),
        SupportedLanguage.ML to mapOf(
            "app_name" to "സ്മാർട്ട് റേഷൻ വിതരണ സംവിധാനം",
            "verify_card" to "റേഷൻ കാർഡ് പരിശോധിക്കുക",
            "scan_qr" to "QR സ്കാൻ ചെയ്യുക",
            "scan_barcode" to "ബാർകോഡ് സ്കാൻ",
            "tap_nfc" to "NFC കാർഡ് ടാപ്പ് ചെയ്യുക",
            "distribute" to "റേഷൻ വിതരണം ചെയ്യുക",
            "confirm_distribution" to "വിതരണം സ്ഥിരീകരിക്കുക",
            "print_receipt" to "രസീത് പ്രിൻ്റ് ചെയ്യുക",
            "face_auth" to "മുഖ തിരിച്ചറിയൽ",
            "verified" to "സ്ഥിരീകരിച്ചു",
            "entitlement" to "അർഹത",
            "remaining" to "ബാക്കി",
            "rice" to "അരി",
            "wheat" to "ഗോതമ്പ്",
            "sugar" to "പഞ്ചസാര",
            "monthly" to "പ്രതിമാസ വിതരണം",
            "three_month" to "3 മാസത്തെ വിതരണം",
            "offline_mode" to "ഓഫ്‌ലൈൻ മോഡ്",
            "complaint" to "പരാതി നൽകുക",
            "audit_log" to "ഓഡിറ്റ് ലോഗ്"
        ),
        SupportedLanguage.MR to mapOf(
            "app_name" to "स्मार्ट रेशन वितरण प्रणाली",
            "verify_card" to "स्मार्ट रेशन कार्ड पडताळा",
            "scan_qr" to "QR कोड स्कॅन करा",
            "scan_barcode" to "बारकोड स्कॅन करा",
            "tap_nfc" to "NFC कार्ड टॅप करा",
            "distribute" to "रेशन वाटप करा",
            "confirm_distribution" to "वाटपाची पुष्टी करा",
            "print_receipt" to "पावती छापा",
            "face_auth" to "चेहरा पडताळणी",
            "verified" to "पडताळणी पूर्ण",
            "entitlement" to "पात्रता",
            "remaining" to "शिल्लक",
            "rice" to "तांदूळ",
            "wheat" to "गहू",
            "sugar" to "साखर",
            "monthly" to "मासिक वाटप",
            "three_month" to "३ महिन्यांचे आगाऊ वाटप",
            "offline_mode" to "ऑफलाइन मोड",
            "complaint" to "तक्रार नोंदवा",
            "audit_log" to "ऑडिट नोंद"
        ),
        SupportedLanguage.BN to mapOf(
            "app_name" to "স্মার্ট রেশন বন্টন ব্যবস্থা",
            "verify_card" to "রেশন কার্ড যাচাই করুন",
            "scan_qr" to "QR কোড স্ক্যান করুন",
            "scan_barcode" to "বারকোড স্ক্যান",
            "tap_nfc" to "NFC কার্ড ট্যাপ করুন",
            "distribute" to "রেশন বন্টন করুন",
            "confirm_distribution" to "বন্টন নিশ্চিত করুন",
            "print_receipt" to "রসিদ প্রিন্ট করুন",
            "face_auth" to "মুখ শনাক্তকরণ",
            "verified" to "যাচাইকৃত",
            "entitlement" to "বরাদ্দ",
            "remaining" to "অবশিষ্ট",
            "rice" to "চাল",
            "wheat" to "গম",
            "sugar" to "চিনি",
            "monthly" to "মাসিক বন্টন",
            "three_month" to "৩ মাসের বন্টন",
            "offline_mode" to "অফলাইন মোড",
            "complaint" to "অভিযোগ দাখিল করুন",
            "audit_log" to "অডিট লগ"
        ),
        SupportedLanguage.GU to mapOf(
            "app_name" to "સ્માર્ટ રાશન વિતરણ સિસ્ટમ",
            "verify_card" to "રાશન કાર્ડ ચકાસો",
            "scan_qr" to "QR કોડ સ્કેન કરો",
            "scan_barcode" to "બારકોડ સ્કેન",
            "tap_nfc" to "NFC કાર્ડ ટેપ કરો",
            "distribute" to "રાશન વિતરણ કરો",
            "confirm_distribution" to "વિતરણની પુષ્ટિ કરો",
            "print_receipt" to "રસીદ પ્રિન્ટ કરો",
            "face_auth" to "ફેસ ઓથેન્ટિકેશન",
            "verified" to "પ્રમાણિત",
            "entitlement" to "હકદાર જથ્થો",
            "remaining" to "બાકી જથ્થો",
            "rice" to "ચોખા",
            "wheat" to "ઘઉં",
            "sugar" to "ખાંડ",
            "monthly" to "માસિક વિતરણ",
            "three_month" to "3 મહિનાનું વિતરણ",
            "offline_mode" to "ઓફલાઇન મોડ",
            "complaint" to "ફરિયાદ નોંધાવો",
            "audit_log" to "ઓડિટ લોગ"
        ),
        SupportedLanguage.PA to mapOf(
            "app_name" to "ਸਮਾਰਟ ਰਾਸ਼ਨ ਵੰਡ ਪ੍ਰਣਾਲੀ",
            "verify_card" to "ਰਾਸ਼ਨ ਕਾਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
            "scan_qr" to "QR ਕੋਡ ਸਕੈਨ ਕਰੋ",
            "scan_barcode" to "ਬਾਰਕੋਡ ਸਕੈਨ ਕਰੋ",
            "tap_nfc" to "NFC ਕਾਰਡ ਟੈਪ ਕਰੋ",
            "distribute" to "ਰਾਸ਼ਨ ਵੰਡੋ",
            "confirm_distribution" to "ਵੰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ",
            "print_receipt" to "ਰਸੀਦ ਪ੍ਰਿੰਟ ਕਰੋ",
            "face_auth" to "ਚਿਹਰੇ ਦੀ ਪਛਾਣ",
            "verified" to "ਤਸਦੀਕ ਸ਼ੁਦਾ",
            "entitlement" to "ਕੁੱਲ ਕੋਟਾ",
            "remaining" to "ਬਾਕੀ",
            "rice" to "ਚੌਲ",
            "wheat" to "ਕਣਕ",
            "sugar" to "ਖੰਡ",
            "monthly" to "ਮਹੀਨਾਵਾਰ ਵੰਡ",
            "three_month" to "3 ਮਹੀਨੇ ਦੀ ਵੰਡ",
            "offline_mode" to "ਆਫ਼ਲਾਈਨ ਮੋਡ",
            "complaint" to "ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ",
            "audit_log" to "ਆਡਿਟ ਲੌਗ"
        ),
        SupportedLanguage.AS to mapOf(
            "app_name" to "স্মাৰ্ট ৰেচন বিতৰণ ব্যৱস্থা",
            "verify_card" to "ৰেচন কাৰ্ড পৰীক্ষা কৰক",
            "scan_qr" to "QR ক’ড স্কেন কৰক",
            "scan_barcode" to "বাৰক’ড স্কেন",
            "tap_nfc" to "NFC কাৰ্ড টেপ কৰক",
            "distribute" to "ৰেচন বিতৰণ কৰক",
            "confirm_distribution" to "বিতৰণ নিশ্চিত কৰক",
            "print_receipt" to "ৰচিদ প্ৰিন্ট কৰক",
            "face_auth" to "মুখৰ চিনাক্তকৰণ",
            "verified" to "যাচাই কৰা হ’ল",
            "entitlement" to "প্ৰাপ্য",
            "remaining" to "অৱশিষ্ট",
            "rice" to "চাউল",
            "wheat" to "গেহু",
            "sugar" to "চেনি",
            "monthly" to "মাহেকীয়া বিতৰণ",
            "three_month" to "৩ মাহৰ বিতৰণ",
            "offline_mode" to "অফলাইন মোড",
            "complaint" to "অভিযোগ দাখিল কৰক",
            "audit_log" to "অডিট ল’গ"
        ),
        SupportedLanguage.OR to mapOf(
            "app_name" to "ସ୍ମାର୍ଟ ରାସନ ବଣ୍ଟନ ପ୍ରଣାଳୀ",
            "verify_card" to "ରାସନ କାର୍ଡ ଯାଞ୍ଚ କରନ୍ତୁ",
            "scan_qr" to "QR କୋଡ ସ୍କାନ କରନ୍ତୁ",
            "scan_barcode" to "ବାରକୋଡ ସ୍କାନ",
            "tap_nfc" to "NFC କାର୍ଡ ଟ୍ୟାପ କରନ୍ତୁ",
            "distribute" to "ରାସନ ବଣ୍ଟନ କରନ୍ତୁ",
            "confirm_distribution" to "ବଣ୍ଟନ ନିଶ୍ଚିତ କରନ୍ତୁ",
            "print_receipt" to "ରସିଦ ପ୍ରିଣ୍ଟ କରନ୍ତୁ",
            "face_auth" to "ମୁହଁ ଚିହ୍ନଟ (Face Auth)",
            "verified" to "ଯାଞ୍ଚ ସଫଳ",
            "entitlement" to "ଅଧିକାର କୋଟା",
            "remaining" to "ବାକି",
            "rice" to "ଚାଉଳ",
            "wheat" to "ଗହମ",
            "sugar" to "ଚିନି",
            "monthly" to "ମାସିକ ବଣ୍ଟନ",
            "three_month" to "୩ ମାସର ବଣ୍ଟନ",
            "offline_mode" to "ଅଫଲାଇନ ମୋଡ",
            "complaint" to "ଅଭିଯୋଗ ଦାଖଲ",
            "audit_log" to "ଅଡିଟ ଲଗ"
        )
    )

    fun getString(key: String, language: SupportedLanguage): String {
        return translations[language]?.get(key)
            ?: translations[SupportedLanguage.EN]?.get(key)
            ?: key
    }
}
